# Setup
The first thing we typically do when dealing with data in Python is to import the `pandas` package and one of its dependencies, `numpy`. 

In [1]:
import pandas as pd
import numpy as np
#import xml.etree.ElementTree as ET


Due to the large size of this file, we store it in a different directory than the one where this notebook lies. If you are not using GitHub, this is a good way to do it as GitHub does not like such large files. 

In [34]:
import os
os.chdir('/Users/jonathanzhu/Documents/ev work/allegheny')
df = pd.read_csv('dhs_service_records_synthesized_final.csv')

## Conduct some simple data inspection

Before doing anything with the data, it is good practice to take a look at a few samples from the dataset. Here, we're going to take a look at the first ten rows and the last seven rows.

In [3]:
df.head()

,synthetic_data,MCI_UNIQ_ID,CALDR_YR,DATE_OF_EVENT,service,GEO_AREA,age,DOB,DOD,GENDER,GENDER_IDENTITY,SEX_ORIENT,LEGAL_SEX,RACE,ETHNICITY,LIVING_ARRANGEMENT,EMPLOYMENT_STATUS,MARITAL_STATUS,EDUCATION_LEVEL,VETERAN_FLAG
0,SYNTHETIC DATA,1626,2021,01/31/2021,Children_Attending_Early_Childhood_Programs_Ma...,NaN,5,NaN,NaN,1~Male,NaN,NaN,NaN,1~White,99~Unknown,NaN,NaN,99~Unknown,9-12~High School (grade 9-12),NaN
1,SYNTHETIC DATA,1626,2021,02/28/2021,Children_Attending_Early_Childhood_Programs_Ma...,NaN,5,NaN,NaN,1~Male,NaN,NaN,NaN,1~White,99~Unknown,NaN,NaN,99~Unknown,9-12~High School (grade 9-12),NaN
2,SYNTHETIC DATA,1626,2021,03/31/2021,Children_Attending_Early_Childhood_Programs_Ma...,NaN,5,NaN,NaN,1~Male,NaN,NaN,NaN,1~White,99~Unknown,NaN,NaN,99~Unknown,9-12~High School (grade 9-12),NaN
3,SYNTHETIC DATA,1626,2021,04/30/2021,Children_Attending_Early_Childhood_Programs_Ma...,NaN,5,NaN,NaN,1~Male,NaN,NaN,NaN,1~White,99~Unknown,NaN,NaN,99~Unknown,9-12~High School (grade 9-12),NaN
4,SYNTHETIC DATA,1626,2021,05/31/2021,Children_Attending_Early_Childhood_Programs_Ma...,NaN,5,NaN,NaN,1~Male,NaN,NaN,NaN,1~White,99~Unknown,NaN,NaN,99~Unknown,9-12~High School (grade 9-12),NaN


In [4]:
df.tail(7)

,synthetic_data,MCI_UNIQ_ID,CALDR_YR,DATE_OF_EVENT,service,GEO_AREA,age,DOB,DOD,GENDER,GENDER_IDENTITY,SEX_ORIENT,LEGAL_SEX,RACE,ETHNICITY,LIVING_ARRANGEMENT,EMPLOYMENT_STATUS,MARITAL_STATUS,EDUCATION_LEVEL,VETERAN_FLAG
7116127,SYNTHETIC DATA,530696,2021,06/30/2021,Suicides,NaN,21,NaN,NaN,2~Female,NaN,NaN,NaN,1~White,99~Unknown,NaN,NaN,99~Unknown,99~Unknown,NaN
7116128,SYNTHETIC DATA,530765,2021,06/30/2021,Suicides,NaN,15,NaN,NaN,2~Female,NaN,NaN,NaN,1~White,99~Unknown,NaN,NaN,99~Unknown,99~Unknown,NaN
7116129,SYNTHETIC DATA,530832,2021,06/30/2021,Suicides,NaN,17,NaN,NaN,1~Male,NaN,NaN,NaN,1~White,99~Unknown,NaN,NaN,99~Unknown,99~Unknown,NaN
7116130,SYNTHETIC DATA,532121,2021,04/30/2021,Suicides,NaN,22,NaN,NaN,2~Female,NaN,NaN,NaN,1~White,99~Unknown,NaN,NaN,1~Single-Never Married,9-12~High School (grade 9-12),NaN
7116131,SYNTHETIC DATA,533991,2021,11/30/2021,Suicides,NaN,16,NaN,NaN,1~Male,NaN,NaN,NaN,1~White,99~Unknown,NaN,NaN,1~Single-Never Married,9-12~High School (grade 9-12),NaN
7116132,SYNTHETIC DATA,534127,2021,07/31/2021,Suicides,NaN,19,NaN,NaN,1~Male,NaN,NaN,NaN,1~White,2~Not Hispanic/Latinx,NaN,NaN,4~Widowed,GRAD~Graduate Degree,NaN
7116133,SYNTHETIC DATA,535156,2021,06/30/2021,Suicides,NaN,24,NaN,NaN,1~Male,NaN,NaN,NaN,1~White,99~Unknown,NaN,NaN,1~Single-Never Married,9-12~High School (grade 9-12),NaN


### Dataframe dimensions, column names, column data types, ranges of column values

To get these, we can easily call some prebuilt attributes that are assigned to pandas dataframes. These help us to understand our data before we even start modifying it.

In [5]:
df.shape

(7116134, 20)

In [6]:
df.columns

Index(['synthetic_data', 'MCI_UNIQ_ID', 'CALDR_YR', 'DATE_OF_EVENT', 'service',
       'GEO_AREA', 'age', 'DOB', 'DOD', 'GENDER', 'GENDER_IDENTITY',
       'SEX_ORIENT', 'LEGAL_SEX', 'RACE', 'ETHNICITY', 'LIVING_ARRANGEMENT',
       'EMPLOYMENT_STATUS', 'MARITAL_STATUS', 'EDUCATION_LEVEL',
       'VETERAN_FLAG'],
      dtype='object')

Pandas dataframes also have a helpful method for easy summarization of the set, which you can call with `df.info()`.

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7116134 entries, 0 to 7116133
Data columns (total 20 columns):
 #   Column              Dtype  
---  ------              -----  
 0   synthetic_data      object 
 1   MCI_UNIQ_ID         int64  
 2   CALDR_YR            int64  
 3   DATE_OF_EVENT       object 
 4   service             object 
 5   GEO_AREA            float64
 6   age                 int64  
 7   DOB                 float64
 8   DOD                 float64
 9   GENDER              object 
 10  GENDER_IDENTITY     float64
 11  SEX_ORIENT          float64
 12  LEGAL_SEX           float64
 13  RACE                object 
 14  ETHNICITY           object 
 15  LIVING_ARRANGEMENT  float64
 16  EMPLOYMENT_STATUS   float64
 17  MARITAL_STATUS      object 
 18  EDUCATION_LEVEL     object 
 19  VETERAN_FLAG        float64
dtypes: float64(9), int64(3), object(8)
memory usage: 1.1+ GB


Another way to check the data types, if you just want that, is to use the `dtypes` attribute of the dataframe.

In [8]:
df.dtypes

synthetic_data         object
MCI_UNIQ_ID             int64
CALDR_YR                int64
DATE_OF_EVENT          object
service                object
GEO_AREA              float64
age                     int64
DOB                   float64
DOD                   float64
GENDER                 object
GENDER_IDENTITY       float64
SEX_ORIENT            float64
LEGAL_SEX             float64
RACE                   object
ETHNICITY              object
LIVING_ARRANGEMENT    float64
EMPLOYMENT_STATUS     float64
MARITAL_STATUS         object
EDUCATION_LEVEL        object
VETERAN_FLAG          float64
dtype: object

We can also find the number of unique entries in the dataframe. This can be important as in some cases we may not want duplicates. In the case of these data from Allegheny County, we actually want to get only unique IDs.

In [9]:
df.nunique()

synthetic_data             1
MCI_UNIQ_ID           533799
CALDR_YR                   1
DATE_OF_EVENT             12
service                   22
GEO_AREA                   0
age                      112
DOB                        0
DOD                        0
GENDER                     3
GENDER_IDENTITY            0
SEX_ORIENT                 0
LEGAL_SEX                  0
RACE                       7
ETHNICITY                  3
LIVING_ARRANGEMENT         0
EMPLOYMENT_STATUS          0
MARITAL_STATUS             7
EDUCATION_LEVEL            8
VETERAN_FLAG               0
dtype: int64

Note to collaborators: the next two code cells are irrelevant with the complete dataset as there are no entries with "SYNTHET" in the synthetic_data column.

In [10]:
#note: I am not sure what 'SYNTHET" versus "SYNTHETIC DATA" means.
#but we split by them anyway.
df.groupby("synthetic_data").count()

,MCI_UNIQ_ID,CALDR_YR,DATE_OF_EVENT,service,GEO_AREA,age,DOB,DOD,GENDER,GENDER_IDENTITY,SEX_ORIENT,LEGAL_SEX,RACE,ETHNICITY,LIVING_ARRANGEMENT,EMPLOYMENT_STATUS,MARITAL_STATUS,EDUCATION_LEVEL,VETERAN_FLAG
synthetic_data,,,,,,,,,,,,,,,,,,,
SYNTHETIC DATA,7116134,7116134,7116134,7116134,0,7116134,0,0,7116134,0,0,0,7116134,7116134,0,0,7116134,7116134,0


In [11]:
df["synthetic_data"].value_counts()

SYNTHETIC DATA    7116134
Name: synthetic_data, dtype: int64

One way to get an overview of the data values is to use another helpful function, `df.describe()`. This will provide several summary statistics for you for each of the columns in the set.

In [12]:
df.describe()

,MCI_UNIQ_ID,CALDR_YR,GEO_AREA,age,DOB,DOD,GENDER_IDENTITY,SEX_ORIENT,LEGAL_SEX,LIVING_ARRANGEMENT,EMPLOYMENT_STATUS,VETERAN_FLAG
count,7.116134e+06,7116134.0,0.0,7.116134e+06,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,2.674853e+05,2021.0,NaN,3.267702e+01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,1.544397e+05,0.0,NaN,2.258095e+01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1.000000e+00,2021.0,NaN,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,1.337730e+05,2021.0,NaN,1.300000e+01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,2.675410e+05,2021.0,NaN,3.000000e+01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,4.010820e+05,2021.0,NaN,4.900000e+01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,5.356080e+05,2021.0,NaN,1.210000e+02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN


In some cases, these are not helpful, like in the IDs portion, having the mean ID value is not important. Same with calendar year, especially since these are all from the same year. But something to note is that the values for the mean, std error, and quartiles will not show up if there are ANY NaN values in the column. So we need to find out where these NaN values are.

## Finding NaN values

In [13]:
df.isna().sum()

synthetic_data              0
MCI_UNIQ_ID                 0
CALDR_YR                    0
DATE_OF_EVENT               0
service                     0
GEO_AREA              7116134
age                         0
DOB                   7116134
DOD                   7116134
GENDER                      0
GENDER_IDENTITY       7116134
SEX_ORIENT            7116134
LEGAL_SEX             7116134
RACE                        0
ETHNICITY                   0
LIVING_ARRANGEMENT    7116134
EMPLOYMENT_STATUS     7116134
MARITAL_STATUS              0
EDUCATION_LEVEL             0
VETERAN_FLAG          7116134
dtype: int64

Note for collaborators: df.isna() and df.isnull() now produce the same results, so the below code cell is not relevant.

In [14]:
df.isnull().sum()

synthetic_data              0
MCI_UNIQ_ID                 0
CALDR_YR                    0
DATE_OF_EVENT               0
service                     0
GEO_AREA              7116134
age                         0
DOB                   7116134
DOD                   7116134
GENDER                      0
GENDER_IDENTITY       7116134
SEX_ORIENT            7116134
LEGAL_SEX             7116134
RACE                        0
ETHNICITY                   0
LIVING_ARRANGEMENT    7116134
EMPLOYMENT_STATUS     7116134
MARITAL_STATUS              0
EDUCATION_LEVEL             0
VETERAN_FLAG          7116134
dtype: int64

We can see the columns ['GEO_AREA', 'DOB', 'DOD', 'GENDER_IDENTITY', 'SEX_ORIENT', 'LEGAL_SEX', 'LIVING_ARRANGEMENT', 'EMPLOYMENT_STATUS', 'VETERAN_FLAG'] have only NaN values.

Note to collaborators: the bottom row that has only NAs is gone with the complete version of the data.
<!--and there seem to be one row that has NA in all columns? usually it can be the first row or last row. But let's verify.-->

In [15]:
df.isna().tail(1)

,synthetic_data,MCI_UNIQ_ID,CALDR_YR,DATE_OF_EVENT,service,GEO_AREA,age,DOB,DOD,GENDER,GENDER_IDENTITY,SEX_ORIENT,LEGAL_SEX,RACE,ETHNICITY,LIVING_ARRANGEMENT,EMPLOYMENT_STATUS,MARITAL_STATUS,EDUCATION_LEVEL,VETERAN_FLAG
7116133,False,False,False,False,False,True,False,True,True,False,True,True,True,False,False,True,True,False,False,True


let's clean up the data frame then, drop last row, drop the columns that only have NAs

Note: I am also not quite sure what the code cell above and below are doing in this context.

In [16]:
df.tail(1)

,synthetic_data,MCI_UNIQ_ID,CALDR_YR,DATE_OF_EVENT,service,GEO_AREA,age,DOB,DOD,GENDER,GENDER_IDENTITY,SEX_ORIENT,LEGAL_SEX,RACE,ETHNICITY,LIVING_ARRANGEMENT,EMPLOYMENT_STATUS,MARITAL_STATUS,EDUCATION_LEVEL,VETERAN_FLAG
7116133,SYNTHETIC DATA,535156,2021,06/30/2021,Suicides,NaN,24,NaN,NaN,1~Male,NaN,NaN,NaN,1~White,99~Unknown,NaN,NaN,1~Single-Never Married,9-12~High School (grade 9-12),NaN


## Removing NA Columns and Rows

To drop NaN values, we can use a simple function called `df.dropna()`.

In [19]:
df.dropna(how='all', inplace=True)
df.shape

(7116134, 20)

Note to collaborators: dropping all NA rows like this has no effect as there are no rows of only NA values.

With this function, the default parameter for a hidden value `axis` removed rows of only NA values. To remove columns, we need to specify the axis.

In [35]:
#we want to remove all the columns that only have NA values
df.dropna(axis=1, how='all', inplace=True)
df.shape

(7116134, 11)

Now if we look at the last row...

In [21]:
df.tail(1)

,synthetic_data,MCI_UNIQ_ID,CALDR_YR,DATE_OF_EVENT,service,age,GENDER,RACE,ETHNICITY,MARITAL_STATUS,EDUCATION_LEVEL
7116133,SYNTHETIC DATA,535156,2021,06/30/2021,Suicides,24,1~Male,1~White,99~Unknown,1~Single-Never Married,9-12~High School (grade 9-12)


Note: I am still going to include code that would remove rows with only NA values, even though it is not relevant for this dataset. Github copilot says that df.dropna(axis=0, how='all', inplace=True) works, and I trust it for the moment.

df.dropna(how="all") would not remove the last row, we need a way to drop the last row 

In [ ]:
#we want to remove any of the rows that have only NA values.
df.dropna(axis=0, how='all', inplace=True)

Now what if we wanted to drop a row with a single NA value? We can simply remove the how='all' parameter and it will remove the rows with at least one NA value.

In [45]:
# df.dropna(inplace=True) # will drop rows with any NA.

 - question: what can you observe from the above result?


 - take a look at 3 random rows, it is important to inspect data beyond the head and tail

In [22]:
# set seed for random function so that we get same rows when re-run the cell
np.random.seed(17)
np.random.randint(2, df.shape[0],3)


array([ 589043, 5539985, 2078088])

In [23]:
np.random.randint(3, df.shape[0],3)

array([ 491929,  828732, 6417139])

In [24]:
# set seed for random function so that we get same rows when re-run the cell
np.random.seed(17)
df.iloc[np.random.randint(0, df.shape[0],3)]

,synthetic_data,MCI_UNIQ_ID,CALDR_YR,DATE_OF_EVENT,service,age,GENDER,RACE,ETHNICITY,MARITAL_STATUS,EDUCATION_LEVEL
589041,SYNTHETIC DATA,364757,2021,10/31/2021,Individuals_Receiving_DHS_Services,54,1~Male,1~White,2~Not Hispanic/Latinx,1~Single-Never Married,99~Unknown
5539983,SYNTHETIC DATA,449747,2021,09/30/2021,Individuals_Receiving_Income_Supports,51,1~Male,1~White,2~Not Hispanic/Latinx,1~Single-Never Married,99~Unknown
2078086,SYNTHETIC DATA,109525,2021,09/30/2021,Individuals_Receiving_Income_Supports,51,1~Male,1~White,2~Not Hispanic/Latinx,1~Single-Never Married,99~Unknown


 - take a look at the record for a specific MCI_UNIQ_ID, say merchant 364757 from above result

In [25]:
df[df['MCI_UNIQ_ID'] == 364757]

,synthetic_data,MCI_UNIQ_ID,CALDR_YR,DATE_OF_EVENT,service,age,GENDER,RACE,ETHNICITY,MARITAL_STATUS,EDUCATION_LEVEL
589034,SYNTHETIC DATA,364757,2021,02/28/2021,Individuals_Receiving_DHS_Services,54,1~Male,1~White,2~Not Hispanic/Latinx,1~Single-Never Married,99~Unknown
589035,SYNTHETIC DATA,364757,2021,03/31/2021,Individuals_Receiving_DHS_Services,54,1~Male,1~White,2~Not Hispanic/Latinx,1~Single-Never Married,99~Unknown
589036,SYNTHETIC DATA,364757,2021,05/31/2021,Individuals_Receiving_DHS_Services,54,1~Male,1~White,2~Not Hispanic/Latinx,1~Single-Never Married,99~Unknown
589037,SYNTHETIC DATA,364757,2021,06/30/2021,Individuals_Receiving_DHS_Services,54,1~Male,1~White,2~Not Hispanic/Latinx,1~Single-Never Married,99~Unknown
589038,SYNTHETIC DATA,364757,2021,07/31/2021,Individuals_Receiving_DHS_Services,54,1~Male,1~White,2~Not Hispanic/Latinx,1~Single-Never Married,99~Unknown
589039,SYNTHETIC DATA,364757,2021,08/31/2021,Individuals_Receiving_DHS_Services,54,1~Male,1~White,2~Not Hispanic/Latinx,1~Single-Never Married,99~Unknown
589040,SYNTHETIC DATA,364757,2021,09/30/2021,Individuals_Receiving_DHS_Services,54,1~Male,1~White,2~Not Hispanic/Latinx,1~Single-Never Married,99~Unknown
589041,SYNTHETIC DATA,364757,2021,10/31/2021,Individuals_Receiving_DHS_Services,54,1~Male,1~White,2~Not Hispanic/Latinx,1~Single-Never Married,99~Unknown
589042,SYNTHETIC DATA,364757,2021,11/30/2021,Individuals_Receiving_DHS_Services,54,1~Male,1~White,2~Not Hispanic/Latinx,1~Single-Never Married,99~Unknown
589043,SYNTHETIC DATA,364757,2021,12/31/2021,Individuals_Receiving_DHS_Services,54,1~Male,1~White,2~Not Hispanic/Latinx,1~Single-Never Married,99~Unknown


In [26]:
df[df['MCI_UNIQ_ID'] == 449747]

,synthetic_data,MCI_UNIQ_ID,CALDR_YR,DATE_OF_EVENT,service,age,GENDER,RACE,ETHNICITY,MARITAL_STATUS,EDUCATION_LEVEL
5539976,SYNTHETIC DATA,449747,2021,01/31/2021,Individuals_Receiving_Income_Supports,51,1~Male,1~White,2~Not Hispanic/Latinx,1~Single-Never Married,99~Unknown
5539977,SYNTHETIC DATA,449747,2021,03/31/2021,Individuals_Receiving_Income_Supports,51,1~Male,1~White,2~Not Hispanic/Latinx,1~Single-Never Married,99~Unknown
5539978,SYNTHETIC DATA,449747,2021,04/30/2021,Individuals_Receiving_Income_Supports,51,1~Male,1~White,2~Not Hispanic/Latinx,1~Single-Never Married,99~Unknown
5539979,SYNTHETIC DATA,449747,2021,05/31/2021,Individuals_Receiving_Income_Supports,51,1~Male,1~White,2~Not Hispanic/Latinx,1~Single-Never Married,99~Unknown
5539980,SYNTHETIC DATA,449747,2021,06/30/2021,Individuals_Receiving_Income_Supports,51,1~Male,1~White,2~Not Hispanic/Latinx,1~Single-Never Married,99~Unknown
5539981,SYNTHETIC DATA,449747,2021,07/31/2021,Individuals_Receiving_Income_Supports,51,1~Male,1~White,2~Not Hispanic/Latinx,1~Single-Never Married,99~Unknown
5539982,SYNTHETIC DATA,449747,2021,08/31/2021,Individuals_Receiving_Income_Supports,51,1~Male,1~White,2~Not Hispanic/Latinx,1~Single-Never Married,99~Unknown
5539983,SYNTHETIC DATA,449747,2021,09/30/2021,Individuals_Receiving_Income_Supports,51,1~Male,1~White,2~Not Hispanic/Latinx,1~Single-Never Married,99~Unknown
5539984,SYNTHETIC DATA,449747,2021,10/31/2021,Individuals_Receiving_Income_Supports,51,1~Male,1~White,2~Not Hispanic/Latinx,1~Single-Never Married,99~Unknown
5539985,SYNTHETIC DATA,449747,2021,11/30/2021,Individuals_Receiving_Income_Supports,51,1~Male,1~White,2~Not Hispanic/Latinx,1~Single-Never Married,99~Unknown


## Conduct some more data inspection at your own time

 - which MCI_UNIQ_ID has the highest number of records among all ID's
 - what is the average number of interactions for clients in the file?
 - how many months did a particular client use the service? say 449747
 - what can you observe from the data?
 


 

## gather all observations, questions, and TODOs

 - columns "DATE_OF_EVENT" is string type and should be date type
 - if we remove the last row, there would be only one value in the "synthetic_data" column, should we remove the column? 
 - MCI_UNIQ_ID column was read into dataframe as numeric, what should we read it in as?
 - do the statistics on the columns make sense? e.g., are there any inconsistencies between age and eduction level? 
 - how many clients used the services in January? How many clients used service by each month?
 - what is the average number of services a client use? 
 - how many clients receive services every month? 
 - do the number of services per client increase over time? 

other data formats that we may teach, TBD

# Basic Transformations

Often times when we encounter data, we find that it is in a format that is a bit clunky to use. Part of EDA will be to make datasets more friendly. Here we will go over four transformations: substitution, generation, outlier removal, and illogical value removal.

## Substitution

For the data entries that have strings in certain columns, like "Individuals_Receiving_DHS_Services", we may need to alter these. Strings can be a bit clunky to work with and are generally read better for plots when we have them in categories. Additionally, we can try and do some mathematical tests on them when we have numerical category labels.